server:
  port: ${blog.service.article.port}
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  qq邮箱配置
  mail:
    host: smtp.qq.com
    username: shiyiblog@qq.com
    password: izdfhkgkrugjhccf
    port: 465
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  datasource:
    name: rediscache
    url: jdbc:mysql://47.98.128.229:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    &serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#  session:
#    store-type: redis
#    redis:
#      flush-mode: immediate
#      namespace: spring:session-beaver
  redis:
    host: 47.98.128.229
    password: dymwan520
    port: 6379
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  #  config-location: classpath:/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.crazy.article.entity
  mapper-locations: classpath:/mapper/*.xml
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
ribbon:
  ConnectionTimeout: 300000
  ReadTimeout: 300000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka
  instance:
    preferIpAddress: true
    instance-id: 127.0.0.1:6001
    #    hostname: ${spring.cloud.client.ipAddress}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    ipAddress: 127.0.0.1
    non-secure-port: 6001
