#logging:
#  level:
#    root: info
blog:
  host:
  service:
    eureka:
      name: eureka
      port: 5555
    article:
      name: article
      port: 6001
    zuul:
      name: zuul
      port: 5001